<section id="income" class="tracker-section">
  <div class="section-heading"><div><p class="eyebrow">Bookings and payouts</p><h2>Income</h2><p>Track Airbnb, Vrbo, direct-booking, and other vacation-rental income for <?= e(date('F Y', strtotime($monthDate))) ?>.</p></div></div>
  <?php if (isset($_GET['imported'])): ?><p class="alert success"><?= (int) $_GET['imported'] ?> rows imported; <?= (int) ($_GET['skipped'] ?? 0) ?> duplicate or unrecognized rows skipped.</p><?php endif; ?>
  <div class="income-metrics">
    <article><span>Gross booking income</span><strong><?= vacation_income_display_money($incomeSummary['gross']) ?></strong></article>
    <article><span>Platform fees</span><strong><?= vacation_income_display_money($incomeSummary['fees']) ?></strong></article>
    <article><span>Net payouts</span><strong><?= vacation_income_display_money($incomeSummary['net']) ?></strong></article>
    <article><span>Operating costs</span><strong><?= vacation_income_display_money($incomeSummary['operating_costs']) ?></strong></article>
    <article class="<?= $incomeSummary['cash_flow'] < 0 ? 'negative' : 'positive' ?>"><span>Cash flow</span><strong><?= vacation_income_display_money($incomeSummary['cash_flow']) ?></strong><small><?= $incomeSummary['nights'] ?> booked night<?= $incomeSummary['nights'] === 1 ? '' : 's' ?><?= $incomeSummary['nights'] && $incomeSummary['gross'] ? ' · ' . vacation_income_display_money($incomeSummary['gross'] / $incomeSummary['nights']) . ' average' : '' ?></small></article>
  </div>
  <div class="income-tools">
    <details><summary>Add income manually</summary><form method="post" class="income-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save_income"><?php include APP_ROOT . '/app/vacation-income-fields.php'; ?><button>Save income</button></form></details>
    <details><summary>Import Airbnb or Vrbo CSV</summary><form method="post" enctype="multipart/form-data" class="import-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="import_income_csv"><label>Platform<select name="platform"><option value="airbnb">Airbnb</option><option value="vrbo">Vrbo</option></select></label><label>CSV report<input type="file" name="income_csv" accept=".csv,text/csv" required></label><p>The importer recognizes common earnings, reservation, fee, date, and payout columns. Duplicate rows are ignored. Compare the imported total with the platform report before relying on it.</p><button>Import report</button></form></details>
  </div>
  <div class="income-ledger"><div class="ledger-title"><div><p class="eyebrow"><?= e(date('F Y', strtotime($monthDate))) ?></p><h3>Income transactions</h3></div><span><?= count($incomeSummary['rows']) ?> entries</span></div><div class="income-table"><div class="income-row income-head"><span>Date</span><span>Platform</span><span>Reservation</span><span>Stay</span><span>Gross</span><span>Fees</span><span>Net</span><span></span></div>
  <?php foreach ($incomeSummary['rows'] as $row): ?><div class="income-row"><span><?= e($row['payout_date'] ?: $row['check_in'] ?: '—') ?></span><span><b class="platform <?= e($row['platform']) ?>"><?= e($platforms[$row['platform']] ?? ucfirst($row['platform'])) ?></b></span><span><strong><?= e($row['reservation_code'] ?: 'Manual entry') ?></strong><small><?= e($row['guest_name'] ?: '') ?></small></span><span><?= e($row['check_in'] ?: '—') ?><?php if ($row['nights'] !== null): ?><small><?= (int) $row['nights'] ?> nights</small><?php endif; ?></span><span><?= vacation_income_display_money((float) ($row['gross_rent'] ?? 0) + (float) ($row['cleaning_fee'] ?? 0)) ?></span><span><?= vacation_income_display_money((float) ($row['platform_fee'] ?? 0)) ?></span><span><strong><?= vacation_income_display_money((float) ($row['net_payout'] ?? 0)) ?></strong></span><details class="income-edit"><summary>Edit</summary><form method="post" class="income-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save_income"><input type="hidden" name="id" value="<?= (int) $row['id'] ?>"><?php $income=$row; include APP_ROOT . '/app/vacation-income-fields.php'; unset($income); ?><button>Save changes</button></form><form method="post" class="income-delete" onsubmit="return confirm('Delete this income entry?')"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete_income"><input type="hidden" name="id" value="<?= (int) $row['id'] ?>"><button>Delete</button></form></details></div><?php endforeach; ?>
  <?php if (!$incomeSummary['rows']): ?><p class="empty-income">No income recorded for this month.</p><?php endif; ?></div></div>
</section>
